services:
  backend:
    build: ./backend # Path to your FastAPI folder
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app # Syncs code so you don't have to rebuild for every change
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: copit_admin
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: copit_db
    ports:
      - "5432:5432"